{{- if .Values.gateway.enabled -}}
{{- if not .Values.hostname }}
{{- fail "gateway requires hostname to be set" }}
{{- end }}
{{- if not .Values.gateway.gatewayClassName }}
{{- fail "gateway requires gatewayClassName to be set" }}
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
{{ include "rancher.labels" . | indent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    {{- if .Values.gateway.listeners }}
    {{- toYaml .Values.gateway.listeners | nindent 4 }}
    {{- else }}
    - name: http
      port: 80
      protocol: HTTP
      hostname: {{ .Values.hostname }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.gateway.tls.enabled }}
    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.hostname }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tls.secretName }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    {{- end }}
{{- end }}
