{{- if .Values.httpRoute.enabled -}}
{{- if not .Values.hostname }}
{{- fail "httpRoute requires hostname to be set" }}
{{- end }}
{{- if not .Values.httpRoute.parentRefs }}
{{- fail "httpRoute requires parentRefs to be set" }}
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
{{ include "rancher.labels" . | indent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    - {{ .Values.hostname }}
  rules:
    {{- range .Values.httpRoute.rules }}
    - backendRefs:
        - name: {{ template "rancher.fullname" $ }}
          port: {{ $.Values.httpRoute.servicePort }}
          weight: 1
      {{- with .matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
